### PR TITLE
"normal" is not listed

### PR DESCRIPTION
**Pull request by sailoog**
"normal" is not listed

https://signalk.org/specification/1.7.0/doc/data_model_metadata.html

### CODE REVIEW

**Comment by tkurki** [comment]
The idea in #18 is that everything outside the non-normal zones is normal. After that change do we need normal? Ping @godind

**Comment by godind** [comment]
Agreed. normal is the default state and it should have empty method array to be “invisible/silent”. So really no need to tamper with or to expose in the UI. It’s up to the consumer to decide what/how to react.

> Any part of the range which is not explicitly within a zone is considered to be normal (the default). As such, zones with a state of normal have no effect and their removal would result in no changes to either displays or alerts.

Sending normal is the mechanism to inform consumer that the data is leaving other states.

**Comment by sailoog** [comment]
Ah OK I had not realized that the plugin sends the "normal" status when none of the other conditions were met, so it makes sense not to add "normal" to the list. I will do some tests tomorrow to check this and close the pull request.

**Comment by sailoog** [comment]
Tested and confirmed. Closing this PR sorry :)

**Pull request closed without merging**
